### ISSUE TITLE
Cytoscape manual overhaul

### ISSUE THREAD

**Issue by khanspers** [nrnb/GoogleSeasonOfDocs#10]
### Background

[Cytoscape](https://cytoscape.org) is a popular network visualization tool used by biologists and bioinformaticians. It has been described as a "swiss army knife" software tool. Both a strength and weakness, it can do LOTS of things, but new users don't know where to start and advances users are constantly discovering new, useful tricks that they wish they had known earlier.

We have an extensive [user manual](http://manual.cytoscape.org/en/stable/) describing all aspects of usage. The manual undergoes updates with every major release, by several editors, for new features added, changes to existing features etc. However, the manual is rarely reviewed in its entirety for overall structure, organization, language and cohesiveness. An overall review and overhaul would be great to improve the quality and usefulness of the manual.

### Goals
* An organized, easy-to-read and accurate user manual
* Consistent and concise language to improve readability and overall usefulness

### Technical Skills
* GitHub wiki markdown syntax
* Cytoscape experience (nice to have)

### Link
* End-user manual: http://manual.cytoscape.org/en/stable/
* Code: https://github.com/cytoscape/cytoscape-manual

### Potential Mentors
Kristina Hanspers

### Contact
[Kristina Hanspers](mailto:kristina.hanspers@gladstone.ucsf.edu)

**Comment by tmnnt** [comment]
Hey,
I just sent a mail to NRNB regarding this project. Could I know how to proceed?

**Comment by khanspers** [comment]
Hi, I don't see your email anywhere, can you let me know where you sent it? Or resend to [my email](mailto:kristina.hanspers@gladstone.ucsf.edu). Thanks!

**Comment by tmnnt** [comment]
Hi Kristina

Here is the mail :-

Hello NRNB team

I am Karthik. I am a deep learning enthusiast from India. I would like to
know how I can contribute to CytoSpace manual overhaul as part of Season of
Docs.


Thank you



PS : I sent this to the following email ID- wmarkuske@ucsd.edu

**Comment by khanspers** [comment]
Hi Karthik, 
I would recommend first reviewing the current manual to get a sense of the scope of the project, with our stated goals in mind. We don't have a detailed plan for the work yet. You can reach out here or email me directly with any questions.
Note that we are particularly looking for applicants with professional experience writing documentation, here's Google's description of the program: 
https://developers.google.com/season-of-docs/

The timeline for this program is as follows: From May 29 - June 28, you’ll have to submit an application to Google for the GSoD projects you are interested in. Organizations will review all applications and select their top picks before Google announces the official accepted projects, on July 30.

Thank you.

Kristina
