### ISSUE TITLE
SynBioHub User Manual

### ISSUE THREAD

**Issue by cjmyers** [nrnb/GoogleSeasonOfDocs#11]
### Background ###

SynBioHub is a design repository for synthetic biology. It is available both as a public website  and as open source software. SynBioHub uses the Synthetic Biology Open Language (SBOL), an open-source standard for representing genetic designs, and also allows sharing design parts from GenBank and FASTA files.

While we have recorded some tutorial videos, such as the one [here](https://youtu.be/KLu_QUuEhgk).  There is really no written user documentation to speak of.  

### Goals ###

- Create user documentation for SynBioHub.
- Develop tutorials for specific use cases.
- Time permitting, documentation for advanced users (i.e., curators and administrators) would be excellent to develop as well.

### Technical Skills ###

GitHub wiki markdown syntax (nice to have)

### Link ###

Current Tutorial Site: http://wiki.synbiohub.org/wiki/Main_Page

### Potential Mentors ###

Chris Myers

### Contact ###

[Chris Myers](mailto:myers@ece.utah.edu)

**Comment by 12VISHESH** [comment]
Hello sir ,
I hope you are doing well and safe!
I am VISHESH TRIPATHI pursuing BTech CSE .I have experienced in data analytics and visualization .I am fluent in python and R language . 
I want to contribute on this project . What I can do further in this project .
I am waiting your response ASAP .
Thanks and regards
VISHESH TRIPATHI

**Comment by cjmyers** [comment]
Hi Vishesh,

That’s great.  Please do consider submitting a proposal.  Recently, we have developed improved documentation for the SynBioHub API, see it here:

https://synbiohub.github.io/api-docs/#about-synbiohub

However, we still need a user documentation separate from this that helps users of SynBioHub’s GUI interface.  This documentation likely would also include the installation and plugin instructions that are currently found in the API documentation.  If you have not already read these papers, it is a good starting point:

https://pubs.acs.org/doi/abs/10.1021/acssynbio.7b00403 

https://pubs.acs.org/doi/abs/10.1021/acssynbio.0c00056 

This paper may also be interesting as it highlights some of the challenges with using SBH and the need for better documentation:

https://academic.oup.com/synbio/article/4/1/ysz016/5520957

Please let me know if you have any questions.

Cheers,
Chris

**Comment by PRUBHTEJ** [comment]
Greetings,
My name is Prubhtej Singh and I'm currently pursuing my Bachelors in Information Technology.
I have a good amount of experience of working in Python programming language and I'm currently learning R language.
I would like to contribute to this project.Requesting your guidance for the same.
Hoping to hear from you soon.
Regards 
Prubhtej Singh

**Comment by cjmyers** [comment]
HI Prubhtej, please see the previous post on this issue for some guidance.

**Comment by PRUBHTEJ** [comment]
Greetings,
Thanks for informing. I'll go through the provided material ,and will definitely let you know if I have any questions.
Regards
Prubhtej Singh

**Comment by PRUBHTEJ** [comment]
Greetings,
I have gone through the existing documentation and it's in a fairly good shape. 
But the documentation is still incomplete, as I have inferred from the existing one.
Also I have observed that the documentation doesn't contain anything regarding the GUI.
I was unable to access the research papers that you have shared in the comment above. Requesting your guidance for the same.
Regards
Prubhtej Singh

**Comment by cjmyers** [comment]
The documentation is indeed only for the API and not the GUI.  The goal of this project is to write a user documentation for the GUI.  

If you email me, I can send you the papers.

**Comment by PRUBHTEJ** [comment]
Greetings
My E-mail ID is prubhtejwadhwa at gmail dot com
Hope to hear from you soon
Regards 
Prubhtej Singh

**Comment by PRUBHTEJ** [comment]
Greetings,
I have gone through the research papers and I am interested in this project. Requesting your guidance for further approach.
Regards
Prubhtej Singh

**Comment by cjmyers** [comment]
Instructions for preparing a proposal are here:

https://developers.google.com/season-of-docs/docs/tech-writer-application-hints

As for the docs themselves, we would likely want to prepare them using Markdown and github pages, so they can be version controlled.

**Comment by 12VISHESH** [comment]
Hello sir ,
I hope you are doing well and safe !
It's quite good using markdown for documentation and it can be version
control.

So can I start writing proposal regarding this project and share it with
you?
I have gone through the paper and present documentation as well .
I am waiting for your reply regarding the same.

Thanks and Regards
VISHESH TRIPATHI

**Comment by cjmyers** [comment]
Yes, you can write the proposal.

**Comment by Tanaya9299** [comment]
Greetings,
I am  Tanaya Mandke a pre-final year student pursuing a Bachelor of Technology Degree in Biotechnology with a minor specialisation in Data Science.
Apart from that I have experience in Robotics and have participated in a few international competitions.
I am interested in contributing to the Google Summer of Docs project offered by your organisation 
I wanted to know if there is any discussion forum or mailing list where I can get to know more about the project and understand the platform.

Currently I am acquainted with python and learning R, I would also like to know what other skills are needed to efficiently complete the project.

Regards,
Tanaya Mandke

**Comment by cjmyers** [comment]
You do not need any programming skills, since GSoD is about technical writing.  You should have some experience in technical writing.  The docs for this project will likely be written in Markdown using github pages.  Some more details are above on this tracker.

**Comment by adityatiwari23** [comment]
Greetings,
I hope you all would be safe and doing well.
I am a student pursuing a Bachelor of Technology Degree in Biomedical Engineering from National Institute of Technology.

I am interested in contributing to the Google Season of Docs project offered by your organisation. As a Biomedical Engineering student, I think I can give my best to this organisation.

I have detailed knowledge of **Git, Github, and Markdown**. Along with that I have a strong hold on programming languages as well.
As you mentioned in the last comment about **experience** in technical writing, what type and amount of experience you are expecting from the Technical Writers.

I wanted to know if there is any discussion channel or mailing list where I can get to know more about the project and understand the working of platform.

An early response would really help me a lot.
Thanks & Regards,
Aditya Tiwari

**Comment by cjmyers** [comment]
From the Google Technical Writer Guide (https://developers.google.com/season-of-docs/docs/tech-writer-guide):

"Able to demonstrate prior technical writing experience by submitting role descriptions and work samples."

As for mailing list, there is this one: synbiohub-dev@googlegroups.com for developers and this one: synbiohub-users@googlegroups.com for users.
