### ISSUE TITLE
Making the Cytoscape.js documentation more accessible to novices

### ISSUE THREAD

**Issue by maxkfranz** [nrnb/GoogleSeasonOfDocs#3]
### Background

[Cytoscape.js](http://js.cytoscape.org/) is a library for graph theory.  It is used in many apps, including those made by the NRNB.

[Typescript](http://www.typescriptlang.org/) is basically type annotations on top of JS.  It allows for type checking at build time.

[JSDoc](http://usejsdoc.org/) is a system for generating docs from JS comments.  It's a lot like Javadoc for Java.  

### Goal

Project goals:  

(1) Convert the documentation for Cytoscape, currently a [JSON specification](https://github.com/cytoscape/cytoscape.js/blob/master/documentation/docmaker.json) with references to Markdown files, to JSDoc comments in the code.

(2) Improve the clarity of the documentation specified in the comments and Markdown files.  The documentation text was written from the perspective of a computer programmer, but it would be great to make the documentation more accessible to novices (e.g. students, researchers in the physical sciences who have little or no formal training in computer science).

Final output:  

- From the JSDoc comments, a Typescript definition file will be generated by code provided to you.  
- A docmaker.json file will also be generated from the JSDoc comments, so that the existing documentation template can still be used.  You can use this provided code to verify your code comment documentation and markdown documentation.

Outcome:  

- This will allow for intellisense/autocomplete for the Cytoscape.js API, Visual Studio Code, Atom, and Sublime Text -- making it much easier to use Cytoscape.js.  
- It will benefit devs who use Typescript, by allowing for easier building of projects using Cytoscape.js. 
- It will also unify the way that specs/definitions for Cytoscape.js are generated:  Everything is built from comments in the code and JSDoc.  This will help to make it easier for people outside of our organisation to contribute to the project.

### Description

N.b. all changes should be on the [`unstable` (dev) branch](https://github.com/cytoscape/cytoscape.js/tree/unstable) of Cytoscape.js.

1. Convert the JSON spec to inline comments in the code in jsdoc format.
1. Review and improve the text in the jsdoc comment and the markdown files.
1. Verify that what you've specified looks as you expect in the built documentation page.  We will guide you through how to do this.

### Skills

Essential : The knack for making technical text more accessible to laymen

Nice to have: Some knowledge of web technology

### Difficulty level 1

This is a straightforward project. 

### Public Repository
https://github.com/cytoscape/cytoscape.js

### Potential mentors

[Max Franz](mailto:maxkfranz@gmail.com)

**Comment by AlexanderPico** [comment]
@maxkfranz Deadline is April 18th. Do you still want to add this one?

**Comment by maxkfranz** [comment]
The description is up-to-date now

**Comment by AlexanderPico** [comment]
I'm going to close this one. Feel free to reuse content from it to make new project ideas directed to GSoD tech writers.

**Comment by gbader** [comment]
Hi Alex - actually, we should open this issue again in case someone is interested.  I think you would have to do this as the person who closed it.  Or we can copy into a new issue.  Thanks.

**Comment by silent-lad** [comment]
@AlexanderPico  @maxkfranz 
I want to contribute to the National Resource for Network Biology during the Google season of docs.
I have experience writing tech blogs and making people understand technical concepts in a layman manner. I also am a very active web developer 
Here's me Medium and Github profile:-
Medium - medium.com/@silentlad
Github - github.com/silent-lad

I want to ask how can I start contributing?

**Comment by Prodyte** [comment]
@AlexanderPico @maxkfranz I am interested in this. is it open for GSoD 2020?

**Comment by maxkfranz** [comment]
Any issue that is open corresponds to a potential project.  If you're interested in a project, submit an application to GSOD.  Thanks for your interest

**Comment by rahul799** [comment]
Hey @maxkfranz, Rahul here. 
I want to work on this project.
Although I have no such technical writing expertise, but I do like to write many blogs related to programming & I am quite familiar with Cytoscape & javascript as I am [selected for GSoC](https://summerofcode.withgoogle.com/projects/#5768352036814848) this year & my project is based on cytoscape.js
Moreover, my primary motivation to work on this project is, I want to help the community to understand cytoscape.js better.
Shall I start drafting a proposal?

**Comment by sidkapoor97** [comment]
Hey @maxkfranz 
I feel I can contribute to the project  in the following way -
1. Make the documentation more friendly and opening for general community instead of just researchers and developers.
2. Convert the JSON object to JSDoc comments.
3. Pick some simple examples from [tutorials](https://github.com/cytoscape/cytoscape-tutorials/wiki) and offer them to the users, or simplify the already existing examples (I would need some help deciding what to do here).

Since this is a pretty straighforward project, I feel keeping the things simple and laymen friendly should do the job. Maybe we can add in new topics such as FAQ to improve the reach to a larger community. I would really appreciate any feedback on this, and thanks @AlexanderPico for referring this project.

**Comment by maxkfranz** [comment]
I encourage anyone who's interested in the project to write a proposal.  I expect that the TS part of the project would take up about half of the project's timespan.  That leaves a significant amount of time to generally make the documentation more accessible to newcomers.  You've all suggested some great ideas for these improvements, and I'll expand upon the list a bit:

- TS support.  The baseline for this is moving over the existing JSON to JSDoc comments.  There may be other improvements that could be made in the text for those comments (better descriptions, more example code snippets, etc.).
- New tutorials.  There are [a number of these on the blog](https://blog.js.cytoscape.org), written by Joseph Stahl and myself.  It would be great to cover new topics or to cover basic topics in more compelling ways (e.g. an interactive step-by-step getting started tutorial, perhaps using one of the online code sharing platforms).
- New demos.  There are a number of [existing demos](https://js.cytoscape.org/#demos).  Some are simple examples, and others give a sense of what fully-fledged Cytoscape web apps are like.
- General improvements to the documentation (e.g. a 'welcome to Cytoscape' section that more thoroughly and gently introduces newcomers to the project).

These are some ideas, but the ideas that you bring to your proposals are what will separate one proposal from another.

If you have any questions, feel free to ask me on Github or by email (maxkfranz@gmail.com).
