### ISSUE TITLE
Network Statistics

### ISSUE THREAD

**Issue by AdamStuart** [nrnb/GoogleSeasonOfDocs#5]
**Background**

- Cytoscape is capable of computing a large number of statistics about a network, including stress, clustering coefficients, or eccentricity. 
- Although wikipedia is a good source of documentation for many of these terms, better documentation would be useful in providing explanation of the concepts and power of these statistics.

**Goal**
- Present theoretical background behind common statistical functions
- Document edge cases and limitations

Technical Skills
- A reasonable understanding of statistics and network notations.

Link
Provide link to current documentation: http://manual.cytoscape.org/en/stable/Network_Analyzer.html

Potential Mentors

Contact

adam.treister@gladstone.ucsf.edu

**Comment by AlexanderPico** [comment]
Please use [template](https://github.com/nrnb/GoogleSeasonOfDocs/issues/1).

**Comment by AdamStuart** [comment]
**Background**

- Cytoscape is capable of computing a large number of statistics about a network, including stress, clustering coefficients, or eccentricity. 
- Although wikipedia is a good source of documentation for many of these terms, better documentation would be useful in providing explanation of the concepts and power of these statistics.

**Goal**
- Present theoretical background behind common statistical functions
- Document edge cases and limitations

Technical Skills
- A reasonable understanding of statistics and network notations.

Link
Provide link to current documentation: http://manual.cytoscape.org/en/stable/Network_Analyzer.html

Potential Mentors

Contact

adam.treister@gladstone.ucsf.edu
